Crud with auth front
loksblnine/clockwise-front pull request #1
Opened 2021-11-17 07:28 UTC by loksblnine

2021-11-17 13:49 UTC, loksblnine commented
feat: add header with auth token for crud operations
na orderList

2021-11-17 13:49 UTC, loksblnine commented
bug fix hz voobshche ono prosto dropalo na refresh page -> ostavil fetch
na OrderList

2021-11-18 15:04 UTC, darinasmile requested changes

2021-11-18 15:04 UTC, darinasmile commented on package.json
> +    "yarn": "^1.22.17"
remove

2021-11-18 15:04 UTC, darinasmile commented on src/components/content/admin-content/customers/InputCustomer.js
> +                                       required //pattern="[A-ZА-Яa-zа-я -]+"
почему валидация закоменчена?

2021-11-18 15:04 UTC, darinasmile commented on src/components/content/admin-content/masters/ListMasters.js
>              await fetch(SERVER_URL + `/deps`, {
это тут не получилось добавить axios ?

2021-11-18 15:04 UTC, darinasmile commented on src/components/content/customer-content/mastersview/MasterView.js
> +            // const response = await fetch(SERVER_URL + `/orders`, {
это еще нужно?

2021-11-18 15:04 UTC, darinasmile commented on src/components/content/getData.js
> +    // instance({
это еще нужно?

2021-11-19 08:30 UTC, loksblnine commented on src/components/content/admin-content/masters/ListMasters.js
>              await fetch(SERVER_URL + `/deps`, {
тут все ок, смотри полный список коммитов

2021-11-19 08:36 UTC, loksblnine commented on src/components/content/customer-content/mastersview/MasterView.js
> +            // const response = await fetch(SERVER_URL + `/orders`, {
net udaleno w next commite

2021-11-19 08:37 UTC, loksblnine commented on src/components/content/getData.js
> +    // instance({
net, udaleno w next commite

2021-11-24 09:47 UTC, closed without merging