Try to redux front
loksblnine/clockwise-front pull request #4
Opened 2021-12-02 08:46 UTC by loksblnine

2021-12-06 14:00 UTC, darinasmile requested changes

2021-12-06 14:00 UTC, darinasmile commented on src/components/AppRouter.js
> +    }, [dispatch])
зачем пустой юз эффект?

2021-12-06 14:00 UTC, darinasmile commented on src/components/content/admin-content/cities/ListCities.jsx
> +            await getCitiesIntoStore(dispatch)
нельзя передавать диспатч как параметр
ты должен диспатчить екшены, например у тебя есть екшн
import { ADD_TODO } from 'constants'

export const addTODO = () => {
  return (dispatch) => {
    dispatch({
      type: ADD_TODO,
      item
    })
  }
}

в компоненте ты должен сделать dispatch(addTODO())

2021-12-06 14:00 UTC, darinasmile commented on src/components/content/master-content/MasterPanel.js
> +    const orders = useSelector((state => state.orders.items))
почему по 2 скобки?

2021-12-06 14:00 UTC, darinasmile commented on src/containers/App.js
> +)(App);
Так а зачем? Это же присоединяет стор и екшены к классовым компонентам. У тебя функциональные компоненты и нет необходимости это делать, все данные доступны в юз селекторе и все екшены могут быть задиспатчены через диспатч от юз диспатча

2021-12-06 14:00 UTC, darinasmile commented on src/store/actions/cityActions.ts
> +export const updateCity = (city: object) => ({
Who is object?

2021-12-06 14:00 UTC, darinasmile commented on src/store/actions/cityActions.ts
> +export const setReadyCities = (bool: boolean) => ({
не называй переменные bool

2021-12-06 14:00 UTC, darinasmile commented on src/store/reducers/cityReducer.ts
> +                isReady: true
ты ж уже передал весь стейт, зачем хардкодить isReady если оно меняется только в одном месте?

2021-12-06 14:00 UTC, darinasmile commented on src/store/reducers/cityReducer.ts
> +            const array = state.items.filter((item: any) => item.city_id !== action.payload.city_id).concat(action.payload)
так а зачем тогда фильтровать и добавлять в конец? Можно же мапом обойти

2021-12-06 14:00 UTC, darinasmile commented on src/store/reducers/customerReducer.ts
> +            const array = state.items.filter((item: any) => item.customer_id !== action.payload.customer_id).concat(action.payload)
переделать везде

2021-12-06 14:00 UTC, darinasmile commented on src/store/reducers/masterReducer.ts
> +            state.items.find(item => item.master_id === action.payload.master_id).deps.splice(state.items.find(item => item.master_id === action.payload.master_id).deps.indexOf(action.payload.city_id
Это точно работает?  Очень сложная функция. Ее необходимо переписать учитывая что стор является not mutable

2021-12-07 09:28 UTC, loksblnine commented on src/components/content/master-content/MasterPanel.js
> +    const orders = useSelector((state => state.orders.items))
это шлак кстати, оно так и не работает же, я это сразу убирал

2021-12-07 09:28 UTC, loksblnine commented on src/containers/App.js
> +)(App);
про это я уже все догадался

2021-12-07 09:29 UTC, loksblnine commented on src/store/reducers/cityReducer.ts
> +                isReady: true
оно потом будет использоваться в дизейбле кнопки, которая отвечает за пагинацию

2021-12-07 09:31 UTC, loksblnine commented on src/store/reducers/masterReducer.ts
> +            state.items.find(item => item.master_id === action.payload.master_id).deps.splice(state.items.find(item => item.master_id === action.payload.master_id).deps.indexOf(action.payload.city_id
проверял много раз + показывал на демо, работает

2021-12-09 12:20 UTC, closed without merging