Registration + redux refactor front
loksblnine/clockwise-front pull request #5
Opened 2021-12-09 12:21 UTC by loksblnine

2021-12-09 14:52 UTC, darinasmile requested changes

2021-12-09 14:52 UTC, darinasmile commented on src/components/AppRouter.js
> +            {role === 3 && authClientRoutes.map(({path, Component}) =>
советую вынести 1, 2, 3 значения ролей в подобие enum (при переходе на тайпскрипт будет легче) + читабельность кода

2021-12-09 14:52 UTC, darinasmile commented on src/components/content/admin-content/cities/EditCity.js
> +    const updateCity1 = async (e) => {
1. это все стоит обернуть в useCallback 
2. async тут уже не нужен
3. updateCity1 - почему 1?

2021-12-09 14:52 UTC, darinasmile commented on src/components/content/admin-content/cities/EditCity.js
> +    const updateCity1 = async (e) => {
тоже самое проверить везде

2021-12-09 14:52 UTC, darinasmile commented on src/components/content/admin-content/customers/ListCustomers.jsx
> +    const handleNextCustomers = (e) => {
useCallback

2021-12-09 14:52 UTC, darinasmile commented on src/components/content/admin-content/masters/ListMasters.jsx
> +    useEffect(() => {
зачем?

2021-12-09 14:52 UTC, darinasmile commented on src/components/content/admin-content/masters/ListMasters.jsx
> +                                        onClick={() => dispatch(deleteCityAtMaster({
вынести в useCallback как константу

2021-12-09 14:52 UTC, darinasmile commented on src/components/content/admin-content/orders/EditOrder.js
> +        body.order.time = `${Number(body.order.time.split(':')[0])}:00`
Я бы советовала для работы с датой и временем использовать какие нибудь библиотеки  типа moment

2021-12-09 14:52 UTC, darinasmile commented on src/components/content/customer-content/LoginForm/LoginForm.js
> +            password: 'passwordsecret',
я так понимаю что это для теста? но в репозиторий этот код не должен попадать

2021-12-09 14:52 UTC, darinasmile commented on src/components/content/customer-content/MasterView/MasterView.js
> +    const handleBack = () => {
useCallback

2021-12-09 14:52 UTC, darinasmile commented on src/components/content/customer-content/RegistrationForm/RegistrationForm.js
> +                    <div className="modal-content"><p>Рабство</p></div>
????

2021-12-09 14:52 UTC, darinasmile commented on src/components/content/master-content/MasterPanel.js
> +            await dispatch(setUserData("masters", email))
зачем тут нужен await?

2021-12-09 14:52 UTC, darinasmile commented on src/components/header/Header.js
> +    useEffect(() => {
зачем?

2021-12-09 15:28 UTC, loksblnine commented on src/components/content/admin-content/masters/ListMasters.jsx
> +    useEffect(() => {
убрал везде

2021-12-09 15:28 UTC, loksblnine commented on src/components/content/admin-content/cities/EditCity.js
> +    const updateCity1 = async (e) => {
исправил наименования

2021-12-09 15:36 UTC, loksblnine commented on src/components/content/admin-content/cities/EditCity.js
> +    const updateCity1 = async (e) => {
убрал асинки и поставил юзколбек где по моему мнению у него есть зависимости и он нужен

2021-12-09 15:38 UTC, loksblnine commented on src/components/content/customer-content/MasterView/MasterView.js
> +    const handleBack = () => {
а я хз какие тут могут быть депенденсис...

    const handleBack = () => {
        history.push({
            pathname: '/',
            state: location.state
        })
    }

2021-12-09 15:38 UTC, loksblnine commented on src/components/content/master-content/MasterPanel.js
> +            await dispatch(setUserData("masters", email))
везде почистил подобного рода чепуху

2021-12-09 15:41 UTC, loksblnine commented on src/components/content/admin-content/orders/EditOrder.js
> +        body.order.time = `${Number(body.order.time.split(':')[0])}:00`
первой миграцией я хочу сделать разделение времени и даты в базе данных и убрать кучу таких костылей с фронта, там я по неопытности поставил таймстамп тип данных....

2021-12-10 10:25 UTC, darinasmile approved these changes

2021-12-10 10:31 UTC, merged