Cloudinary front+feat show password on log-in+regi forms
loksblnine/clockwise-front pull request #7
Opened 2021-12-14 12:59 UTC by loksblnine

2021-12-14 14:28 UTC, darinasmile requested changes

2021-12-14 14:28 UTC, darinasmile commented on src/components/content/customer-content/OrderForm/OrderForm.jsx
> +        if (e?.target?.files[0].size < 8 * 1024 * 1024) {
Максимальный размер лучше вынести в константу

2021-12-14 14:28 UTC, darinasmile commented on src/components/content/customer-content/OrderForm/OrderForm.jsx
> +    const makeBeautiful = (length) => {
???

2021-12-15 07:43 UTC, loksblnine commented on src/components/content/customer-content/OrderForm/OrderForm.jsx
> +    const makeBeautiful = (length) => {
я не нашел в бутстрапе как в семантик-юи количество итемов на строку, пришлось лепить самому(

2021-12-16 15:58 UTC, darinasmile approved these changes

2021-12-16 16:03 UTC, merged