Filter orders front
loksblnine/clockwise-front pull request #8
Opened 2021-12-15 13:33 UTC by loksblnine

2022-01-05 12:06 UTC, darinasmile requested changes

2022-01-05 12:06 UTC, darinasmile commented on src/components/content/admin-content/orders/ListOrders.jsx
> +                {!openFilter ? <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
Лучше выносить svg иконки в отдельные компоненты

2022-01-05 12:06 UTC, darinasmile commented on src/components/content/admin-content/orders/ListOrders.jsx
> +                                   key="date-from" required pattern="[0-9]{4}.[0-9]{2}.[0-9]{2}"
паттерны лучше повыносить в константы и переиспользовать

2022-01-05 12:06 UTC, darinasmile commented on src/components/content/client-content/ClientPanel.js
> +                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
вынести в отдельный компонент

2022-01-05 12:06 UTC, darinasmile commented on src/components/content/customer-content/OrderForm/OrderForm.jsx
> +                        <option value="8:00">8:00</option>
оу, может это хоть в массив какой-то вынести?

2022-01-05 12:06 UTC, darinasmile commented on src/components/content/master-content/MasterPanel.js
> +                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
отдельный компонент

2022-01-10 07:07 UTC, loksblnine commented on src/components/content/admin-content/orders/ListOrders.jsx
> +                {!openFilter ? <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
![image](https://user-images.githubusercontent.com/81150413/148728950-00635075-f855-46a8-a9c1-8d7c5c3a24e4.png)
они в следующем пр имеют такой вид

2022-01-11 11:47 UTC, darinasmile approved these changes
Аппрувлю при условии что иконки действительно все будут переиспользоваться

2022-01-11 12:10 UTC, merged