Oauth2 front
loksblnine/clockwise-front pull request #9
Opened 2022-01-05 15:25 UTC by loksblnine

2022-01-11 13:43 UTC, darinasmile requested changes

2022-01-11 13:43 UTC, darinasmile commented on src/components/content/admin-content/blog/CreateArticle.js
> +        if (e.target?.files[0]?.type.split('/')[0] === "image") {
стоит добавить еще ограничение по размеру файла

2022-01-11 13:43 UTC, darinasmile commented on src/components/content/admin-content/orders/ListOrders.jsx
> +                {!openFilter ? <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
а обещал в этом пулл реквесте повыносить svg в компоненты/константы

2022-01-11 13:43 UTC, darinasmile commented on src/components/content/customer-content/LoginForm/LoginForm.jsx
> +                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
вынести

2022-01-11 13:43 UTC, darinasmile commented on src/store/actions/blogActions.ts
> +            method: "get",
get ловер кейсом, PUT в 27 строке аперкейсом, не консистентно

2022-01-11 13:43 UTC, darinasmile commented on src/utils/constants.js
> +export const ARROWS_SVG = {
Вынести в отдельный файл svg константы

2022-01-12 10:29 UTC, loksblnine commented on src/components/content/admin-content/orders/ListOrders.jsx
> +                {!openFilter ? <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
sadge(

2022-01-13 11:53 UTC, darinasmile approved these changes

2022-01-13 12:04 UTC, merged